# Generated by Django 5.2 on 2025-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='contact_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
