# Generated by Django 5.2 on 2025-06-16 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_surveyresponse_contactsubmission_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parking_spaces', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('has_showers', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_repair_shop', models.BooleanField(default=False)),
                ('has_fuel', models.BooleanField(default=False)),
                ('cleanliness_rating', models.FloatField(default=0)),
                ('food_rating', models.FloatField(default=0)),
                ('safety_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TruckStopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('food_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('safety_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('parking_availability', models.CharField(choices=[('full', 'Full'), ('limited', 'Limited'), ('available', 'Available')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.truckstop')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('conditions', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('truck_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='main_app.truckstop')),
            ],
        ),
    ]
