# Generated by Django 5.2 on 2025-06-16 21:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_truckstop_userfeedback_truckstopreview_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
