# Generated by Django 5.2 on 2025-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_adminloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
