# Generated by Django 5.2 on 2025-07-30 17:40

from django.db import migrations


def populate_entry_ids(apps, schema_editor):
    WaitlistEntry = apps.get_model('main_app', 'WaitlistEntry')
    
    # Get all entries ordered by creation date
    entries = WaitlistEntry.objects.all().order_by('created_at')
    
    for index, entry in enumerate(entries, 1):
        entry.entry_id = f"WL-{index:03d}"
        entry.save()


def reverse_populate_entry_ids(apps, schema_editor):
    WaitlistEntry = apps.get_model('main_app', 'WaitlistEntry')
    WaitlistEntry.objects.all().update(entry_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_add_waitlist_entry_id_no_unique'),
    ]

    operations = [
        migrations.RunPython(populate_entry_ids, reverse_populate_entry_ids),
    ]
