# Generated by Django 5.2 on 2025-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_populate_waitlist_entry_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
