# Generated by Django 5.2 on 2025-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_add_waitlist_entry_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
