# Generated by Django 5.2 on 2025-07-30 18:11

from django.db import migrations


def populate_contact_entry_ids(apps, schema_editor):
    ContactSubmission = apps.get_model('main_app', 'ContactSubmission')
    ContactUs = apps.get_model('main_app', 'ContactUs')
    
    # Populate ContactSubmission entries
    submissions = ContactSubmission.objects.all().order_by('submitted_at')
    for index, submission in enumerate(submissions, 1):
        submission.entry_id = f"CS-{index:03d}"
        submission.save()
    
    # Populate ContactUs entries
    contacts = ContactUs.objects.all().order_by('created_at')
    for index, contact in enumerate(contacts, 1):
        contact.entry_id = f"CU-{index:03d}"
        contact.save()


def reverse_populate_contact_entry_ids(apps, schema_editor):
    ContactSubmission = apps.get_model('main_app', 'ContactSubmission')
    ContactUs = apps.get_model('main_app', 'ContactUs')
    ContactSubmission.objects.all().update(entry_id=None)
    ContactUs.objects.all().update(entry_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_add_contact_entry_ids_step1'),
    ]

    operations = [
        migrations.RunPython(populate_contact_entry_ids, reverse_populate_contact_entry_ids),
    ]
