# Generated by Django 5.2 on 2025-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_populate_contact_entry_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
